package itukraine.com.ua.bestmobile.dao;

import com.j256.ormlite.field.DatabaseField;

public class Playlist {

    @DatabaseField
    public String name;
    @DatabaseField
    public String totalTime;
    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    public Playlist() {
        // needed by ormlite
    }

    public Playlist(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "Name: " + name + " Total time " + totalTime;
    }
}
