package itukraine.com.ua.bestmobile.dao;

import com.j256.ormlite.field.DatabaseField;

public class Song {

    @DatabaseField
    public String title;
    @DatabaseField
    public String artist;
    @DatabaseField
    public String album;
    @DatabaseField
    public String path;
    @DatabaseField
    public String duration;
    // id is generated by the database and set on the object automatically
    @DatabaseField(generatedId = true)
    int id;


    public Song() {
    }

    @Override
    public String toString() {
        return "Song{" +
                "title='" + title + '\'' +
                ", artist='" + artist + '\'' +
                ", album='" + album + '\'' +
                ", path='" + path + '\'' +
                ", duration='" + duration + '\'' +
                '}';
    }
}
